### ISSUE TITLE
Phusion Passenger 5 breaks default :request_type

### ISSUE THREAD

**Issue by donapieppo** [toyokazu/omniauth-shibboleth#14]
With passenger 4 request.env has 'eppn' and all the shibboleth attributes. 
With passenger 5 request.env has only "HTTP_EPPN" and "HTTP_XXXXXX" for each xxxxxx attribute.
In order to use omniauth-shibboleth with passenger 5 I had to use the

:request_type => 'header'

configuration.
Just in case someone has the same issue.

**Comment by toyokazu** [comment]
Thank you for your report.
Do you think that the default should be changed to 'header' or keep it as 'env' for the time being? (While I still use Passenger 4 in the production environment... ;) )

If many of the users want to set 'header' as default, I would like to change it.

Best Regards,

**Comment by donapieppo** [comment]
In Readme.md is written
`You understand the issues using ShibUseHeaders`
I don't know if there's issues with 'request_type: header' that should discourage it's' use.

**Comment by toyokazu** [comment]
In Passenger, the attributes are passed from mod_passenger to Passenger Agents by its own protocol and converted to environment variables. It does not poisoned by the end user request (HTTP request from browsers). However, if you use proxy based approach (ShibUseHeaders), for example, you have Apache as a front end and mod_proxy_balancer to pass the requests to the backend servers, e.g. thin or unicorn server, the HTTP request header might be easily edited by the end user because any HTTP headers are basically pass through the Apache without any explicit filter setting. So, the proxy based approach basically has a security problem.

In Passenger 5, I guess that it is the same as Passenger 4 (sorry I don't confirm it yet). (If it is true) even if you use request_type: header, there will be no security problem I think. Only the notation is changed. You can safely use request_type: header with Passenger 5. In this case, you don't need to use ShibUseHeaders.

Best Regards,
