### ISSUE TITLE
Accepts a user with a null extern_uid

### ISSUE THREAD

**Issue by Aethylred** [toyokazu/omniauth-shibboleth#16]
We had an issue with the SP not requesting HTTP_EPPN correctly when authenticating users, this meant some users were logging in with a null extern_uid

```
May 25, 2015 17:49: (OAuth) saving user X@site.one from logi
n with extern_uid => X@site.one
June 03, 2015 11:22: (OAuth) saving user Y@site.two from login wi
th extern_uid =>
June 03, 2015 11:35: (OAuth) saving user Y@site.two from login with extern_uid =>
June 03, 2015 11:37: (OAuth) saving user Z@site.three from login with extern_uid =>
June 03, 2015 14:42: (OAuth) saving user Y@site.two from login with extern_uid =>
June 03, 2015 15:20: (OAuth) saving user A@site.one from login with extern_uid => A@site.one
```

This meant users Y and Z had the same null extern_uid and kept logging in and getting the same 'identity'

**Comment by Aethylred** [comment]
The expected outcome would be that users with a null extern_uid would be rejected and not able to log in.

The null HTTP_EPPN was a misconfiguration of the SP on our Shibboleth Registry, but the omniauth module did not respond as expected when receiving an improper value.

**Comment by toyokazu** [comment]
Hi,

I think that OmniAuth just provides Auth Hash to the application after the authentication process. The authentication results (success/failure) is basically handled by the application. If you need to prohibit login of users who do not provide uid, you have to check the uid existence in your application as the following:

session[:user][:uid].nil? || session[:user][:uid].empty?

If you are using omniauth for some existing application like gitlab (you seem to use gitlab, right?) and you can not easily modify your application, it may be desirable to give some alert by omniauth. However, what you want to do here? I think that all omniauth can do is to set some kind of string into uid, because the authentication (in this case Shibboleth auth) is succeeded and it must be redirect back to the application. It will not help you.

Here, for example, gitlab seems to have options to prevent auto creation of users with extern_uid. Please refer the following document.

http://doc.gitlab.com/ce/integration/omniauth.html

If you set allow_single_sign_on to false or block_auto_created_users to true and do not permit the creation of a null uid user, the problem should be resolved.

Does it make sense?

Regards

**Comment by Aethylred** [comment]
Yes we're using GitLab, I'll create a ticket there as well.

We set up the following require in the Apache config:

```
require shib-attr eppn ~ ^.+$
```

Which has the desired effect.

**Comment by toyokazu** [comment]
Sorry to be late reply ;)
Thank you for your comment.
I understand what you want to do.

I think some people may want to keep empty uid because some applications do not require uid, e.g. several publisher site does not require uid but organization name. So I would like to add your requirement by option, :fail_with_empty_uid. When you set the option 'true', it will fail after the authentication success. How do you think that?

I temporarily make a branch 'add_fail_with_empty_uid'. I am sorry that I do not have gitlab environment to test it. If you can check it and agree with this approach, I would like to merge it to master branch.

Best Regards

**Comment by Aethylred** [comment]
That would be very helpful.

**Comment by toyokazu** [comment]
Thank you for your comment.
I would like to merge the branch to [master](https://github.com/toyokazu/omniauth-shibboleth/commit/114e327818f954994bb61074a24d077ee4e8117e) and push a new gem to rubygems.org.
If some of you have experienced any problem with this update, please let me know. > to all

Now, I would like to close this issue.
